### ISSUE TITLE
Property 'libraries' is misspelled or does not exist.

### ISSUE THREAD

**Issue by dmitry-weirdo** [Ozsie/detekt-maven-plugin#169]
According to these warnings 

```
Property 'style>ForbiddenPublicDataClass' is deprecated. Rule migrated to `libraries` ruleset plugin.
Property 'style>LibraryCodeMustSpecifyReturnType' is deprecated. Rule migrated to `libraries` ruleset plugin.
Property 'style>LibraryEntitiesShouldNotBePublic' is deprecated. Rule migrated to `libraries` ruleset plugin.
```

I moved these rules to `libraries`, which is conforming to `detekt-1.22.0.json`:

```yaml
libraries:
  active: true

  ForbiddenPublicDataClass:
    active: true
    excludes: [ '**' ]
    ignorePackages:
      - '*.internal'
      - '*.internal.*'

  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: [ '**' ]

  LibraryEntitiesShouldNotBePublic:
    active: true
    excludes: [ '**' ]
```

But the plugin execution is now falling with 
```
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.22.0:check (default) on project rss-app: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.22.0:check failed: Run failed with 2 invalid config properties.
[ERROR]         - Property 'libraries' is misspelled or does not exist.
```

The same happens if I add `formatting` rules:
```
- Property 'formatting' is misspelled or does not exist.
```

# Related issues

https://github.com/detekt/detekt/pull/5360 — this seems to be the PR where these rules have been refactored.

https://github.com/detekt/detekt/pull/5548 — this says it should provide examples for avoiding this, but it will be gradle plugin, not maven plugin.

I think the updated doc link is here — https://detekt.dev/docs/next/rules/libraries/.

and it says

> Note: The libraries rule set is not included in the detekt-cli or Gradle plugin.
> 
> To enable this rule set, add detektPlugins "io.gitlab.arturbosch.detekt:detekt-rules-libraries:$version" to your Gradle dependencies or reference the detekt-rules-libraries-jar with the --plugins option in the command line interface.
>

https://github.com/detekt/detekt/discussions/5304 — this issue says that we have to add more gradle dependencies eg for `formatting`, but how to do this when using the maven plugin?

How should we add the non-default rulesets when using the maven plugin?
